model: SentenceRepresentationProber
dataset_class: SentenceProberDataset
experiment_dir: exps/morphology
subword_pooling: lstm
model_name: bert-base-multilingual-cased
dropout: 0.2
mask_positions: []

mlp_layers: [50]
mlp_nonlinearity: ReLU

epochs: 200
batch_size: 128
optimizer: Adam

sort_data_by_length: true
shuffle_batches: true
save_metric: dev_acc

numpy_random_seed: 1
torch_random_seed: 1
